"""control

Revision ID: 6af0628551aa
Revises: b07c8be3810d
Create Date: 2024-09-13 11:00:43.416748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af0628551aa'
down_revision: Union[str, None] = 'b07c8be3810d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('mark', sa.String(), nullable=False),
    sa.Column('sub', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('wire_id', sa.Integer(), nullable=True),
    sa.Column('gaz_id', sa.Integer(), nullable=True),
    sa.Column('tip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gaz_id'], ['gaz.id'], ),
    sa.ForeignKeyConstraint(['tip_id'], ['tip.id'], ),
    sa.ForeignKeyConstraint(['wire_id'], ['wire.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('control', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_control_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_control_id'))

    op.drop_table('control')
    # ### end Alembic commands ###
