"""clear

Revision ID: 7cbfe5b47316
Revises: 618086e7cb12
Create Date: 2024-08-20 19:26:09.658266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbfe5b47316'
down_revision: Union[str, None] = '618086e7cb12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('robot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('robot_clear_nozzle', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('robot_clear_add_nozzle', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('robot_clear_intestine', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('robot', schema=None) as batch_op:
        batch_op.drop_column('robot_clear_intestine')
        batch_op.drop_column('robot_clear_add_nozzle')
        batch_op.drop_column('robot_clear_nozzle')

    # ### end Alembic commands ###
