"""collector add

Revision ID: 7e8fd0db00cc
Revises: d893f94f6490
Create Date: 2024-09-15 13:56:14.677427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8fd0db00cc'
down_revision: Union[str, None] = 'd893f94f6490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control', schema=None) as batch_op:
        batch_op.drop_column('start_count')

    # ### end Alembic commands ###
