"""Added Table mode

Revision ID: b07c8be3810d
Revises: 546ba0f054c3
Create Date: 2024-09-09 11:13:58.284048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07c8be3810d'
down_revision: Union[str, None] = '546ba0f054c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_mudguard')
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_shift', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.drop_column('number_shift')

    op.create_table('_alembic_tmp_mudguard',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mudguard_matireal', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
