"""collector

Revision ID: d893f94f6490
Revises: 6af0628551aa
Create Date: 2024-09-15 08:03:41.138456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd893f94f6490'
down_revision: Union[str, None] = '6af0628551aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userwaamer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_collector', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userwaamer', schema=None) as batch_op:
        batch_op.drop_column('is_collector')

    # ### end Alembic commands ###
